### ISSUE TITLE
The problem is that large extensions are not displayed correctly.

### ISSUE THREAD

**Issue by DameerGamlet** [hedgieinsocks/gnome-extension-lineup#2] opened 2023-05-04 18:36 UTC
Now:
![image](https://user-images.githubusercontent.com/74682814/236297370-719e1790-bc8c-4abd-ab08-098bf32ccd4c.png)

How this extension looks like:
![image](https://user-images.githubusercontent.com/74682814/236297542-60375fdf-4afa-47a6-afb5-de54ba63387d.png)

The extension is cool, but it compresses important extensions too much.

**Comment by DameerGamlet** [comment] 2023-05-04 18:37
The "Vitals" and "Todo.txt" extensions hide values to a single point (which is not what I would like to see)

**Comment by hedgieinsocks** [comment] 2023-05-04 20:08
@DameerGamlet Thank you for trying out this extension and reporting the bug. I looks like these extensions start with either zero or < 50 width and thus get under the knife. I have committed a quick fix to the master branch https://github.com/hedgieinsocks/lineup/commit/80fa63f13c615d06622cfa86b2993773cc793854 and it seems it's working fine. Is it possible for you to modify the updated line 27 in your ~/.local/share/gnome-shell/extensions/lineup@hedgie.tech/extension.js  and give it a test after a relogin? If you confirm that it's good, I'll update on ego.

**Comment by DameerGamlet** [comment] 2023-05-05 03:57
Thanks for the quick response, I'll check everything by the evening

**Comment by hedgieinsocks** [comment] 2023-05-05 13:22
Actually, I've made a few more tweaks, and the new version 6 is now on ego for you to update (might require gnome-session restart)

**Comment by DameerGamlet** [comment] 2023-05-05 14:53
After updating:
![image](https://user-images.githubusercontent.com/74682814/236492436-b99bde8f-bd8f-4f70-8e42-b4084637ac29.png)

Still, the vitals extension is too big (but the todo.txt now works properly).

If I turn the minimum up to 50, everything comes back the way it was.
![image](https://user-images.githubusercontent.com/74682814/236492728-54c4046d-7172-462b-956d-5d31c33179ae.png)

Rebooted the system.

**Comment by DameerGamlet** [comment] 2023-05-05 14:56
I just updated. Last updated 1 hour ago.

**Comment by hedgieinsocks** [comment] 2023-05-05 15:17
Hmm, that is very weird. I have double-checked just now and it is ok for me. Enable-disable, lock-unlock, login-relogin, still all is fine. 

![image](https://user-images.githubusercontent.com/26518927/236494613-e0489ac6-6df7-4bd2-85a7-f4efbd6d800f.png)

Since you have confirmed that the issue persists after relogin after the last update, then I'm kinda lost why this indicator is getting cut if it must be skipped. The only idea is that it is generated with the width between min and max values and only then expands but by that time it is already hardcoded. 

If that is true, I'll have to come up with some kind of whitelist option in the settings.

**Comment by hedgieinsocks** [comment] 2023-05-06 14:18
If you are still willing to give it another try, I've pushed version 8 to ego. It contains extra options which might help your case. 

![image](https://user-images.githubusercontent.com/26518927/236629278-dcf85da7-1a9b-46b6-abf9-92992684973d.png)

Suggested course of actions:

- update
- disable vitals
- relogin
- set delay in lineup settings to e.g. 2
- enable vitals

If vitals still appears cut off, then you can try to whitelist it by name:

- type in exclude 'vitals' (case insensitive)
- disable and then enable vitals

I do hope it helps. If not, sorry it took your time and effort. Anyway, I'm grateful for your cooperation!

**Comment by DameerGamlet** [comment] 2023-05-06 17:59
now:
![image](https://user-images.githubusercontent.com/74682814/236639696-cd766a8c-4cdd-4622-833d-33d41efcb477.png)

**Comment by DameerGamlet** [comment] 2023-05-06 18:00
before:
![image](https://user-images.githubusercontent.com/74682814/236639736-9ee023b0-c66a-4601-93f1-f5a939863824.png)

after:
![image](https://user-images.githubusercontent.com/74682814/236639906-f12043fb-7b52-4726-b799-7c9ecbf56c12.png)

**Comment by DameerGamlet** [comment] 2023-05-06 18:03
settings:
![image](https://user-images.githubusercontent.com/74682814/236639954-0fad0ccd-41b0-4921-bb3f-a9e09259e558.png)

 I did everything according to your instructions.  But I don't see any noticeable improvement over what it was

**Comment by hedgieinsocks** [comment] 2023-05-07 06:53
Thank you for giving it another try. The main idea of the extension is not to lower the horizontal spacing between indicators. You can do it via Just Perfection or Status Area Horizontal Spacing (both support Gnome 44). This extension attempts to force **standard** indicators from various providers to have the same width so the tray looks consistent and there are no extra gaps to catch the eye of a perfectionist. 

This is how wide the default Clipboard History indicator:

![33](https://user-images.githubusercontent.com/26518927/236662068-4845621a-16ad-4ae2-aa07-171f411049c8.png)

This is how narrow the default KeePassXS indicator created by AppIndicator and KStatusNotifierItem Support:

![44](https://user-images.githubusercontent.com/26518927/236662070-7605f842-c4f5-4e9f-8481-1293fbae6bf8.png)

This is when I enable Lineup and set the width to 40 - Clipboard History indicator becomes narrow:

![55](https://user-images.githubusercontent.com/26518927/236662221-8acc31be-047b-45a0-94d5-2b7a2fcfd4cb.png)

This is when I enable Lineup and set the width to 50 - KeePassXC becomes wide:

![50](https://user-images.githubusercontent.com/26518927/236661405-d48e1af6-20ce-43de-adf0-4898f1fda52e.png)

------

So, the changes in horizontal spacing will not be quite prominent, and they are not the main goal. And since you are using a few wide non-standard indicators, you are not seeing any improvement in spacing and aesthetics unlike in my minimalistic setup. 

Still, I once again thank you for reporting the bug and trying my fixes. This will surely help someone whose needs can be addressed by this extension.

**Comment by DameerGamlet** [comment] 2023-05-07 19:31
![image](https://user-images.githubusercontent.com/74682814/236698779-1c45c04a-aac2-4b21-bf4b-a9edfdc2b8e8.png)
![image](https://user-images.githubusercontent.com/74682814/236698792-2c535204-ea6f-4513-a021-ff67d5aeb49d.png)

**Closed as not planned** 2023-09-15 05:37 UTC
Labels: bug
